Fix upload JSON dataset
DashAISoftware/DashAI pull request #104
Opened 2023-06-16 23:06 UTC by maximi4321

# Summary

This PR solves issue #97

## Type of change

- Bug fix.

## Changes

- Added `name` parameter to `jsondataloader.json`
- Corrected the description of the `name` parameter in `csvdataloader.json`, so it uses text instead of html.

## How to Test

1. Go to `DashAI/DashAI/front` and run `yarn build`
2. Go back to `DashAI/` and run `python -c "import DashAI;DashAI.run()"`
3. Navigate to the datasets tab
4. Click "New Dataset"
5. Select "TabularClassificationTask" as your task
6. Select "JSONDataloader" as your dataloader
7. Upload `DashAI/back/example_datasets/irisDataset.json` as your dataset
8. Give it a name or optionally leave blank
9. Click "Save" and the dataset should be uploaded succesfully

## Screenshots

[jsontest.webm](https://github.com/DashAISoftware/DashAI/assets/53657198/d3374bda-f8d0-407e-9eaa-1d54093104a3)

2023-06-18 18:28 UTC, pbadillatorrealba requested changes
I simplified some messages in order to make them more consistent and easy to understand with the things that a common DashAI will see.
@maximi4321 , please review them and check if they are correct.

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/csvdataloader.json
> +          "description": "Custom name to register your dataset, if left blank, the name of the uploaded file will be used.",
"Custom name to register your dataset. If no name is specified, the name of the uploaded file will be used",

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +          "description": "Custom name to register your dataset, if left blank, the name of the uploaded file will be used.",
```suggestion
          "description": "Custom name to register your dataset. If no name is specified, the name of the uploaded file will be used",,
```

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +          "description": "The data has to be inside a key in your JSON files. Write the name of the key that constains the data.",
"Name of key that contains the data in the JSON files."

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +          "description": "You must specify which columns will be the output according to the task. By default the last column is selected.",
"Output column(s) of the dataset. By default, the last column is selected as output."

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +          "error_msg": "Need to specify the name(s) of the key(s) that defines the output columns of the data.",
"The specified column name(s) is(are) not valid."

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +          "description": "If your data has folders that define the splits select 'true', otherwise 'false'.",
"True allows you to indicate that the data are divided into "train", "test" and "validation" folders. False otherwise, indicates there are no previous divisions of the dataset."
```suggestion
          "description": "Option that allows you to indicate that the data are divided into "train", "test" and "validation" folders. Otherwise, it is assumed that there are no previous divisions of the dataset.",
```

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +          "error_msg": "Need to select 'true' if you have folders that define the splits, otherwise 'false'.",
"You must specify true or false."
```suggestion
          "error_msg": "You must specify true or false.",
```

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +            "description": "The training set contains the data to be used for training a model. Must be defined between 0 and 100% of the data.",
My guess is that this information (what is train, validation test sets) should be in the app, not in the parameter description.
I should abbreviate this line to: 
"Percentage of the data that will be assigned to produce the training dataset (in the range 0 to 1, where 0 is 0% and 1 is 100%)."

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +            "description": "The test set contains the data that will be used to evaluate a model. Must be defined between 0 and 100% of the data.",
Same here: 
"Percentage of the data that will be assigned to produce the test dataset (in the range 0 to 1, where 0 is 0% and 1 is 100%)."

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +            "error_msg": "The validation set size must be between 0 and 1.",
Percentage of the data that will be assigned to produce the validation dataset (in the range 0 to 1, where 0 is 0% and 1 is 100%).

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +              "description": "Determines whether the data will be shuffle when defining the sets or not. It must be true for shuffle the data, otherwise false.",
```suggestion
              "description": "This option indicates that the data will be randomly shuffled prior to generating the training, validation and test sets.",
```

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +              "error_msg": "Must be true or false, choose if you want to shuffle the data when separating the sets.",
```suggestion
              "error_msg": "Shuffle should be True or False.",
```

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +              "description": "A seed defines a value with which the same mixture of data will always be obtained. It must be an integer greater than or equal to 0.",
```suggestion
              "description": "Positive integer that defines a randomness seed, which is a mechanism that allows to control randomness and make the results repeatable, even if within the same process there are random steps.".,
```

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +              "error_msg": "Must be true or false, choose if you want to separate the data into sets with the same proportion of samples per class as the original set or not.",
```suggestion
              "error_msg": "Must be true or false.",
```

2023-06-18 18:28 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/params_schemas/jsondataloader.json
> +              "description": "Defines whether the data will be proportionally separated according to the distribution of classes in each set.",
"This option ensures that when dividing the dataset into train, test, and validation sets, the original distribution of labels in the input dataset will be preserved in each of the resulting datasets. This option is applicable only to classification problems"

2023-06-19 20:59 UTC, maximi4321 commented
The latest commit modifies the messages.

I think this improves the messages, makes them more concise and better explained and also considers the context in which the user would be when viewing them.

2023-06-19 21:39 UTC, cristian-tamblay approved these changes

2023-06-19 21:39 UTC, merged