Added sample method to DashAIDataset
DashAISoftware/DashAI pull request #108
Opened 2023-06-20 16:31 UTC by nataliabrc

# Summary
Added a sample method to DashAIDataset class. This method generates samples from a dataset with three different options: retrieve the first n rows, the last n rows or n random rows.

The purpose of this change is to be able to retrieve samples from a dataset when using the Prediction tab to show them to the user.

## Changes
- Added sample method to DashAIDataset in `dashai_dataset.py`
- Added new test in `test_dashai_dataset.py`

## How to Test
Run `pytest ./tests/back/dataloaders/test_dashai_dataset.py`

2023-06-30 01:59 UTC, pbadillatorrealba requested changes
Some minor comments about types and tests

2023-06-30 01:59 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/classes/dashai_dataset.py
> +        seed: int | None = None,
This notation is not compatible with python 3.8 :((

You have to change it to:

```suggestion
        seed: Union[int, None] = None,
```

And import as `from typing import Union`

2023-06-30 01:59 UTC, pbadillatorrealba commented on DashAI/back/dataloaders/classes/dashai_dataset.py
> +    ):
Question: what kind of object returns, a python dict, dashai dataset or huggingface dataset?

Please add a return type to make this explicit

2023-06-30 01:59 UTC, pbadillatorrealba commented on tests/back/dataloaders/test_dashai_dataset.py
> +def test_dashaidataset_sample(dashaidataset_created: list):
Could you also test for n!=1?

2023-07-04 17:18 UTC, nataliabrc commented
All requested changes are completed 👌

2023-07-05 18:57 UTC, pbadillatorrealba commented
Nice!

I guess that merging this pr would not affect the current release, what do you think @cristian-tamblay ?

2023-07-06 16:22 UTC, cristian-tamblay commented
Good to merge!

2023-07-31 14:38 UTC, merged