Fix/documentation generation
DashAISoftware/DashAI pull request #135
Opened 2023-07-25 13:57 UTC by cristian-tamblay

# Summary

This PR updates the documentation generation on pshinx including DashAI about and quick start.

## Type of change

- Documentation.

## Changes

- Enabled documentation update on staging push (to check if its working correctly before the main release, we will disable it after merging)
- Added "About" documentation
- Added "Quick Start" linked to README.rst

## How to Test

We need to merge the PR to check if github pages is working correctly

## Screenshots

Screenshots from my local RST compiler

![image](https://github.com/DashAISoftware/DashAI/assets/30818944/3e219c87-4e6a-47bd-9d6f-f867932a069c)
![image](https://github.com/DashAISoftware/DashAI/assets/30818944/f93704f5-5a61-4dbb-8791-32ba782c5ac9)

2023-07-25 14:03 UTC, cristian-tamblay commented
Current bug:
![image](https://github.com/DashAISoftware/DashAI/assets/30818944/ef7539a6-7ecd-4553-a4cd-88227c54a04e)
This looks ugly, next push i'll fix it

2023-07-27 02:24 UTC, pbadillatorrealba requested changes
Great work!

I left many small comments and some ideas to improve de documentation.

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +The following is a step-by-step guide on how to implement a new model in DashAI, specifically the Helsinki-NLP/opus-mt-en-en-es model. It is important to consider that we are working on the staging v
```suggestion
The following is a step-by-step guide on how to implement a new model in DashAI, specifically the :code:`Helsinki-NLP/opus-mt-en-en-es` model. It is important to consider that we are working on the staging version of June 11, 2023.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +The first part is to create the class of the model inside the corresponding folder, as in this case it is a transformer we will use the hugging_face folder.
```suggestion
The first part is to create the class of the model inside the corresponding folder, as in this case it is a transformer we will use the :code:`hugging_face` folder.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +Verify or create in case there is no class in the models folder that will be used to associate models to a particular task. Then, as shown in the image, the TranslationModel class will be created and
```suggestion
Verify or create in case there is no class in the models folder that will be used to associate models to a particular task. Then, as shown in the image, the :code:`TranslationModel` class will be created and in :code:`COMPATIBLE_COMPONENTS` it will be specified to which task it belongs. In this way all the models compatible with the translation task must inherit from this class.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +1. Fit: method to train the model, receives a DashAIDataset.
```suggestion
1. :code:`.fit`: method to train the model, receives a :code:`DashAIDataset`.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +2. Predict: method to predict with the model already trained, receives a DashAIDataset.
```suggestion
2. :code:`.predict`: method to predict with the model already trained, receives a :code:`DashAIDataset`.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +Inside the parameters folder is the folder models_schemas which contains all the parameter schemas. The JSON that will work as a schema for the model must be created and incorporated in the get_schem
```suggestion
Inside the parameters folder is the folder models_schemas which contains all the parameter schemas. The JSON that will work as a schema for the model must be created and incorporated in the :code:`get_schema` method of the model class.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +3. Save: method to save the model, it receives a string that represents the path where the model will be saved.
```suggestion
3. :code:`.save`: method to save the model, it receives a string that represents the path where the model is saved.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +4. Load: method to load the model, it receives a string that represents where the model is saved.
```suggestion
4. :code:`.load`: method to load the model, it receives a string that represents where the model is saved.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +Extra methods can be added depending if the model needs it or not, as well as some extra attributes of the model, as it happens in the case of transformers that need to ask for more information.
Interesting point. Perhaps we should indicate that any extra method should be "private" and therefore start with a "`_`" (and obviously try to apply it to what we currently have).

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +Finally, several tests must be defined to corroborate the correct functioning of the model, for this it is always necessary to load in DashAIDataset format some dataset that is useful for the model.
```suggestion
Finally, several tests must be defined to corroborate the correct functioning of the model, for this it is always necessary to load in :code:`DashAIDataset` format some dataset that is useful for the model. The ideal is to ensure that the 4 methods discussed in step 4 work successfully, in addition to the creation of the schema of step 3.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
Perhaps in the description of the class and of each of the required methods (`fit`, `predict`, `save`, `load`)  we could include code segments of the translation model.

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
Also, perhaps it would be a good idea for the implementation to be somewhat more basic and generalizable than the translator (which has many extra methods). 

And at the end add: if you want to see a more advanced implementation, like for example a translator, then visit the translation model.

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/about.rst
> +In conclusion, DashAI represents a groundbreaking tool that bridges the gap between users and Machine Learning, making advanced algorithms and models accessible without the need for programming exper
```suggestion
In conclusion, DashAI represents a groundbreaking tool that bridges the gap between users and Machine Learning, making advanced algorithms and models accessible without the need for programming expertise. Through its open source nature and emphasis on community collaboration, DashAI is poised to revolutionize ML adoption in Chile, Latin America, and beyond 🌠.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on README.rst
> +This project is sponsored by the National Center for Artificial Intelligence CENIA FB210017, and the Millennium Institute for Foundational Data Research (IMFD) ICN17_002.
Add links to the institutions:

```suggestion
This project is sponsored by the `National Center for Artificial Intelligence - CENIA <https://cenia.cl/en/>`_ (FB210017), and the `Millennium Institute for Foundational Data Research - IMFD <https://imfd.cl/en/>`_ (ICN17_002).
```

Maybe also add the universities here?

2023-07-27 02:24 UTC, pbadillatorrealba commented on README.rst
> +The core of the development is carried out by students from the Computer Science Department of the University of Chile and the Federico Santa Maria Technical University.
... as well as CENIA, IMFD and external developers. ?

2023-07-27 02:24 UTC, pbadillatorrealba commented on README.rst
> +
```suggestion
To see the full list of contributors, visit in `Contributors <https://github.com/DashAISoftware/DashAI/graphs/contributors>`_ the DashAI repository on Github.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/conf.py
>  html_theme = "sphinx_rtd_theme"
What do you think about using [furo theme](https://sphinx-themes.org/sample-sites/furo/)?

```suggestion
html_theme = "furo"
```
![imagen](https://github.com/DashAISoftware/DashAI/assets/22802485/6419b3f8-618a-4b83-b8e7-85a477fe1486)

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/about.rst
> +===================================================================
I added several levels of headings to give the page a less flat structure.

```suggestion
=======================================================
DashAI: Empowering Machine Learning without Programming
=======================================================
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/about.rst
```suggestion

Main Features
=============

Below is a list of the main features offered by DashAI.
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/about.rst
> +============================
```suggestion
Versatility in Task Handling
----------------------------
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/about.rst
> +=========================
```suggestion
Seamless Interoperability
-------------------------
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/about.rst
> +=================================================
```suggestion
Embracing Open Source and Community Collaboration
-------------------------------------------------
```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/about.rst
> +===============================================
```suggestion
Emphasizing the Interactive Graphical Interface
-----------------------------------------------

```

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +==========
Rather than user guide I would use the term Developer's Guide (from what appears in the guide).

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/getting_started/user_guide.rst
> +==========
Perhaps a user guide could be screenshots of each step of the process to load datasets and run experiments.

2023-07-27 02:24 UTC, pbadillatorrealba commented on docs/source/index.rst
Maybe add a note saying that the documentation needs to be completed and invite anyone who wants to contribute?

```suggestion
..note: 
    This is a preliminary version of the DashAI documentation. 
    There are still several pages to be written. If you want to contribute to the documentation or the project, open a pr in the `project repository <https://github.com/DashAISoftware/DashAI>`_ and feel free to ask any questions you may have!
```

2023-07-27 15:30 UTC, merged