Model migrations with Alembic
DashAISoftware/DashAI pull request #141
Opened 2023-08-10 16:39 UTC by MillarayVVS

# Summary

Adds Alembic to use for migrations and modifies dataset model deleting task_name.

## Type of change

- Back end new feature.
- Documentation.

## Changes

- Install Alembic for migration management.
- Adds How to make migrations with Alembic to the README file
- Remove task_name from dataset model with migrations
- Modify tests and validations for dataset model.

## How to Test

- Run ```pip install -r requirements.txt```
- Run ```alembic upgrade head``` to apply migrations scripts
- Run ```alembic current``` to check the current migration status

2023-08-10 20:24 UTC, cristian-tamblay requested changes
Seems good, i left some minor changes and we should be good to merge. Also, why merge it to data-studio instead of staging?

2023-08-10 20:24 UTC, cristian-tamblay commented on tests/back/api/test_datasets.py
> +    print(response)
Please avoid merging code with prints

2023-08-10 20:24 UTC, cristian-tamblay commented on tests/back/dataloaders/dashaidataset/test/data-00000-of-00001.arrow
What are these files?

2023-08-10 20:24 UTC, cristian-tamblay commented on alembic/README
Is this file needed?

2023-08-10 20:24 UTC, cristian-tamblay commented on README.rst
> +    $ alembic upgrade head
Do i run these commands from the root or inside the alembic folder?

2023-08-17 16:59 UTC, MillarayVVS commented on tests/back/api/test_datasets.py
> +    print(response)
Resolved in recent commit

2023-08-17 17:01 UTC, MillarayVVS commented on README.rst
> +    $ alembic upgrade head
You should run these commands from the root, I added a new instruction in the README file on the recent commit.

2023-10-05 13:00 UTC, cristian-tamblay commented
Please Resolve conflicts so we can merge this! You can follow the `Use the command line to resolve conflicts` on the box below

2023-10-10 17:58 UTC, closed without merging