New random_forest_regressor and ada_boost_classifier classes
DashAISoftware/DashAI pull request #157
Opened 2023-09-26 01:32 UTC by MartinParedesR

# Summary

1. Added ada_boost_classifier class with its parameters.
2. Added random_forest_regressor class.

## Type of change

- Back end new feature.

## How to Test

The tests are not ready yet.

2023-10-05 12:43 UTC, cristian-tamblay commented on DashAI/back/models/scikit_learn/random_forest_regressor.py
I think regressors aren't supported by SklearnLikeModel because the prediction uses predict_proba, not implemented in Sklearn's Regressors

2023-10-05 12:43 UTC, cristian-tamblay requested changes
AdaBoost is correctly implemented, but i think we should delete the regrssor because its not compatible

2023-10-10 17:11 UTC, pbadillatorrealba commented
I think this should be corrected by making perhaps two wrappers, one for classification and one for regression. But that is for another pr.

2023-10-10 17:12 UTC, pbadillatorrealba commented
@MartinParedesR , please also check that the classifier you implemented is working correctly when executing a task on the front end.

2023-12-24 16:41 UTC, pbadillatorrealba commented
@MartinParedesR , what is the status of this change?

2024-02-07 17:10 UTC, cristian-tamblay commented
Stale, closing

2024-02-07 17:10 UTC, closed without merging