Back/initial api
DashAISoftware/dashAI pull request #2
Opened 2022-09-27 22:27 UTC by Riul1999

# Changes

## Enpoints implemented:
- /info -> Indicate if the api is online.
- /dataset/upload -> Loads the sent dataset and returns the compatible models.
- /selectModel/{model} -> Returns the parameters of the sent model.
- /selectedParameters/{model} -> Set the parameters of the sent model.
- /experiment/run/0 -> Execute the experiment.
- /experiment/results/0 -> Return the results of the experiment.

## Task implemented:
- NumericClassificationTask : List List Int -> Int
- TextClassificationTask: String -> Int

## Model implemented (file.py and schema):
- KNN (Numeric)
- SVM (Numeric)
- RandomForest (Numeric)
- NumericalWrapperForText (Text)

2022-09-29 15:04 UTC, cristian-tamblay requested changes
Hay algunos comentarios generales para pensar cosas a futuro, pero ojalá resolver la mayor cantidad de problemas antes de hacer un merge a main.

2022-09-29 15:04 UTC, cristian-tamblay commented on back/.gitignore
> +borrar.py
Que es borrar.py?

2022-09-29 15:04 UTC, cristian-tamblay commented on back/Models/classes/numericClassificationModel.py
> +    """
Hay algo que implementar acá?

2022-09-29 15:04 UTC, cristian-tamblay commented on back/Models/classes/numericalWrapperForText.py
> +        kwargs["n_gram"] = (ngram_min_n,ngram_max_n)
Seguro que el parametro es n_gram? Creo que lo testié una vez y necesitaba el parametro ngram_range en vez de n_gram

2022-09-29 15:04 UTC, cristian-tamblay commented on back/Models/classes/sklearnLikeModel.py
> +            joblib.dump(self, bytes_container)
No entiendo que hace esto, por qué si no tiene nombre entonces el save guarda BytesIO(), esto es vacío?

2022-09-29 15:04 UTC, cristian-tamblay commented on back/Models/classes/sklearnLikeModel.py
> +            joblib.dump(self, filename)
No deberia haber un return acá?

2022-09-29 15:04 UTC, cristian-tamblay commented on back/Models/classes/textClassificationModel.py
> +    """
Se implementará a futuro?

2022-09-29 15:04 UTC, cristian-tamblay commented on back/Models/parameters/models_schemas/knn.json
> +{
Quizas algo general para todos estos archivos, a futuro quizas ver cómo entregar estos schemas en multiples idiomas

2022-09-29 15:04 UTC, cristian-tamblay commented on back/TaskLib/task/taskMain.py
> +    experimentResults = []
La task se encarga de las ejecuciones y los resultados? No sería mejor implementar una clase "session" o algo del estilo? Quizas sea bueno darle una vuelta

2022-09-29 15:04 UTC, cristian-tamblay commented on back/TaskLib/task/taskMain.py
> +            }
Esto está bastante complejo, quizas repensar en alguna otra iteración el crear la clase "session" o "execution"

2022-09-29 15:04 UTC, cristian-tamblay commented on back/TaskLib/task/textClassificationTask.py
> +    Abstarct class for text classification tasks.
Es abstract?

2022-09-29 15:04 UTC, cristian-tamblay commented on back/main.py
> +        session_info["task"] = Task.createTask(session_info["task_name"])
Como se asocia session_id con task_name y task? Quizas hacer 2 diccionarios extras que asocien id ->names e id->tasks puede ser buena idea (o quizas hay una mejor forma)

2022-09-29 15:04 UTC, cristian-tamblay commented on back/main.py
> +    return {"models": ["knn","naive_bayes","random_forest"]}
Como el front sabe cuales son las ids de los datasets ya disponibles? Hay que fijar quien lo define, el front o el back

2022-09-29 15:04 UTC, cristian-tamblay commented on back/main.py
> +def available_models_for_task(model_name):
Esto no deberia ser task_name en vez de model_name?

2022-09-29 15:04 UTC, cristian-tamblay commented on back/main.py
> +        return f"{parent} not found"
Es buena idea retornar distintos status_code, por ejemplo, si la respuesta contiene error, enviar status = 400 o un not found 404, cosa que el front pueda manjear mejor estos casos

2022-10-03 15:13 UTC, Riul1999 commented on back/.gitignore
> +borrar.py
Ni idea, yo creo que no es necesario tenerlo en el gitignore

2022-10-03 15:15 UTC, Riul1999 commented on back/Models/classes/numericClassificationModel.py
> +    """
Agregue un método parse_single_input_from_string para parsear un ejemplo que mande el usuario para "jugar" con el modelo, fuera de eso por ahora no se necesita nada más en esa clase

2022-10-03 15:16 UTC, Riul1999 commented on back/Models/classes/numericalWrapperForText.py
> +        kwargs["n_gram"] = (ngram_min_n,ngram_max_n)
Cambiado a n_gram_range, un error que venia del otro repo

2022-10-03 15:17 UTC, Riul1999 commented on back/Models/classes/sklearnLikeModel.py
> +            joblib.dump(self, bytes_container)
Esto es para retornar los bytes que representan el modelo, luego los bytes se guardan en la db. No hemos examinado aun otra forma de guardar los modelos

2022-10-03 15:18 UTC, Riul1999 commented on back/Models/classes/sklearnLikeModel.py
> +            joblib.dump(self, filename)
No, porque en el caso que si hayan ingresado un filename los bytes se guardan directamente en un archivo con el nombre ingresado

2022-10-03 15:19 UTC, Riul1999 commented on back/Models/classes/textClassificationModel.py
> +    """
Agregue un método parse_single_input_from_string para parsear un ejemplo que mande el usuario para "jugar" con el modelo, fuera de eso por ahora no se necesita nada más en esa clase

2022-10-03 15:20 UTC, Riul1999 commented on back/Models/parameters/models_schemas/knn.json
> +{
Podría tenerse una base en ingles y luego traducirla a otros idiomas, lo anotare en el notion.

2022-10-03 15:25 UTC, Riul1999 commented on back/TaskLib/task/taskMain.py
> +    experimentResults = []
Si, esto es más que nada porque no se tiene la noción de resultados fuera de las ejecuciones porque usamos el método score que proveen los modelos de sklearn. Cuando agreguemos la noción de metricas si se podrian sacar los resultados.

2022-10-03 15:30 UTC, Riul1999 commented on back/TaskLib/task/textClassificationTask.py
> +    Abstarct class for text classification tasks.
No, para la demo agregamos un método parse_single_input_from_string, para poder parsear la sentencia de "juego" que ingresa el usuario. La idea es que esta clase define el comportamiento particular que tiene la clasificación de texto frente a otras task, lo que por ahora no es mucho.

2022-10-03 15:38 UTC, Riul1999 commented on back/main.py
> +        session_info["task"] = Task.createTask(session_info["task_name"])
La idea es que para un session_id dado (queda por hacer el generar un nuevo cada vez que se sube un dataset) se le asocie un task (por ahora asociamos task_name porque no tenemos un metodo en task que retorne su nombre)

2022-10-03 15:41 UTC, Riul1999 commented on back/main.py
> +    return {"models": ["knn","naive_bayes","random_forest"]}
Hay que implementar otro endpoint que entrega esta info, un diccionario que asocie id a dataset_name, dataset_description y dataset_task y luego en el front si el usuario selecciona un dataset de ejemplo mando el id

2022-10-03 15:44 UTC, Riul1999 commented on back/main.py
> +def available_models_for_task(model_name):
Es cierto, pero creo que este endpoint no se usa, voy a confirmar con maximiliano y en dicho caso lo elimino de la API

2022-10-03 15:44 UTC, Riul1999 commented on back/main.py
> +        return f"{parent} not found"
Si, lo voy a dejar anotado en el notion (aunque creo que es parte de uno de los pitch)

2022-10-03 15:57 UTC, Riul1999 commented on back/main.py
> +def available_models_for_task(model_name):
Confirmado

2022-10-04 00:12 UTC, Riul1999 commented on back/TaskLib/task/taskMain.py
> +            }
Ok, agregado al notion

2022-10-07 14:41 UTC, cristian-tamblay approved these changes

2022-10-07 14:42 UTC, merged