Separate experiment API from experiment table.
DashAISoftware/DashAI pull request #37
Opened 2023-04-05 02:00 UTC by pbadillatorrealba

This pr has as main focus to separate the experiments APIs (CRUD) from the experiments table component. Changes: 

- Moved the experiments API. It is now located in `src/api/experiments` and is initially typed.

- The ExperimentsTable component now imports these methods and executes them in an asynchronous wrapper inside the component.

- Interactivity is added through snackbars/toast. These can be seen when the getExperiments request fails and when an experiment is deleted (correctly or incorrectly).

- Typescript is enabled on the front end.

- Interfaces are declared for the main application data: Experiment, Dataset and Run. These can be found in the `src/types` folder.

If this change is approved, it is expected that the rest of the APIs will be declared in the same or similar way as this one; that is, a module with the API declaration and the component imports the functions that it requires.

2023-04-05 17:48 UTC, cristian-tamblay requested changes

2023-04-05 17:48 UTC, cristian-tamblay commented on DashAI/front/src/api/experiment.ts
If we are switching to typescript on some files, shouldn't we change all the jsx files to ts? What do you think about mixing javascript and typescript?

2023-04-05 17:48 UTC, cristian-tamblay commented on DashAI/front/src/api/experiment.ts
> +  const response = await api.delete(`experiment/${id}`);
I think we are missing the path here. We also have a .env defining api paths, maybe we should use them here.
```suggestion
  const response = await api.delete(`/api_v1/experiment/${id}`);
```

2023-04-05 17:48 UTC, cristian-tamblay commented on DashAI/front/src/api/experiment.ts
> +  const response = await api.patch(`experiment/${id}`, formData);
```suggestion
  const response = await api.patch(`/api_v1/experiment/${id}`, formData);
```

2023-04-06 13:20 UTC, pbadillatorrealba commented on DashAI/front/src/api/experiment.ts
As far as I understand it is not necessary. Just type the ts files and their dependencies. 
It appears that changes may be gradual.
In this case it was only necessary to type the interfaces and the API file.

2023-04-06 14:10 UTC, cristian-tamblay approved these changes

2023-04-06 16:30 UTC, merged