Validators and task changes
DashAISoftware/DashAI pull request #63
Opened 2023-05-11 15:44 UTC by Oziel14

This PR depends on #60 

Summary List:

- Validators have been added to the basetask class, which checks that the types and cardinality of the columns that act as input or output are correct, also a method called prepare to task has been added that transforms some columns to the types needed by the task.
- To the tabular classification task the types and cardinalities compatible with the validator were added, and the corresponding changes were made in prepare for tasks to transform its labels column to the corresponding type.
- Tests were also carried out to test some of the mentioned functionalities.

2023-05-11 16:32 UTC, Oziel14 commented
There are errors but in the precommit that come from the front end when pulling staging changes.

2023-05-15 19:42 UTC, pbadillatorrealba commented
The same as #60  we need a title and descriptions of what you are changing to know how to review.

2023-05-17 02:46 UTC, Oziel14 commented
This PR depends on #60.

Summary List:
- Validators have been added to the basetask class, which checks that the types and cardinality of the columns that act as input or output are correct, also a method called prepare to task has been added that transforms some columns to the types needed by the task.
- To the tabular classification task the types and cardinalities compatible with the validator were added, and the corresponding changes were made in prepare for tasks to transform its labels column to the corresponding type.

2023-05-22 21:36 UTC, pbadillatorrealba commented
I'm wating to #60 to review this pr ⏳.

2023-05-23 02:44 UTC, Oziel14 commented
Ready for review

2023-05-24 19:27 UTC, pbadillatorrealba requested changes
Nice pr!
Relatively short and easy to review.

I left some comments with respect to the code, test and documentation styles.

2023-05-24 19:27 UTC, pbadillatorrealba commented on tests/back/tasks/test_tasks.py
>              datasetdict[split] = datasetdict[split].change_columns_type(tipos)
This is in spanish :(

Also, Does it work? Is there a "Categorico" type?

2023-05-24 19:27 UTC, pbadillatorrealba commented on tests/back/tasks/test_tasks.py
> +        tabular_task.validate_dataset_for_task(datasetdict, name_datasetdict)
In general, only the line of code that raises the exception should be inside the context manager pytest.raises. This is because if another exception of the same type is raised in an earlier part of the code, pytest.raises will catch it as if it were the one it was expecting. Also I recommend to separate the code sections and logics with newlines.
Below I suggest how to solve this:

```python
def test_wrong_type_task():
    dashai_dataset_csv = dashaidataset_from_csv("iris_extra_feature.csv")
    
    inputs_columns = [
        "SepalLengthCm",
        "SepalWidthCm",
        "PetalLengthCm",
        "PetalWidthCm",
    ]
    outputs_columns = ["Species", "StemCm"]
    datasetdict = to_dashai_dataset(
        dashai_dataset_csv, inputs_columns, outputs_columns
    )
    col_types = {"Species": "Categorical"}
    
    for split in datasetdict:
        datasetdict[split] = datasetdict[split].change_columns_type(col_types)
        
    tabular_task = TabularClassificationTask.create()
    name_datasetdict = "Iris"

    with pytest.raises(TypeError):
        tabular_task.validate_dataset_for_task(datasetdict, name_datasetdict)
```

Note that I also changed `tipos` to `col_types` and `Categorico` to `Categorical`.

2023-05-24 19:27 UTC, pbadillatorrealba commented on tests/back/tasks/test_tasks.py
> +    assert True
Already having a pytest.raises it is not necessary to have an assert, since pytest correctly detects this function as a test.

```suggestion
```

2023-05-24 19:27 UTC, pbadillatorrealba commented on tests/back/tasks/test_tasks.py
> +        tabular_task.validate_dataset_for_task(datasetdict, name_datasetdict)
Same comments as before:

```suggestion
def test_not_prepared_task():
    dashai_dataset_csv = dashaidataset_from_csv("iris.csv")
    inputs_columns = [
        "SepalLengthCm",
        "SepalWidthCm",
        "PetalLengthCm",
        "PetalWidthCm",
    ]
    outputs_columns = ["Species"]
    name_datasetdict = "Iris"
    
    datasetdict = to_dashai_dataset(
        dashai_dataset_csv, inputs_columns, outputs_columns
    )
    tabular_task = TabularClassificationTask.create()
    
    with pytest.raises(TypeError):
        tabular_task.validate_dataset_for_task(datasetdict, name_datasetdict)
```

2023-05-24 19:27 UTC, pbadillatorrealba commented on tests/back/tasks/test_tasks.py
> +    assert True
To test a function that does not raises anything, you could use a try/catch block. In try, you execute the code. If the code fails, pytest.fail is executed, which reports the error:

```suggestion
    try:
        tabular_task.validate_dataset_for_task(datasetdict, name_datasetdict)
    except Exception as e:
        pytest.fail(f"Unexpected error in test_prepare_task: {repr(e)}")
```

2023-05-24 19:27 UTC, pbadillatorrealba commented on tests/back/tasks/iris_extra_feature.csv
Why there are several pr that changes this files?

2023-05-24 19:27 UTC, pbadillatorrealba commented on DashAI/back/tasks/base_task.py
> +        """Method to change the column types to suit the task
The description should be in infinitive and end with a period.

```suggestion
        """Change the column types to suit the task requirements.
```

2023-05-24 19:27 UTC, pbadillatorrealba commented on DashAI/back/tasks/base_task.py
> +
Include a comment that indicate if the method will create a copy or with mutate the original object.

2023-05-24 19:27 UTC, pbadillatorrealba commented on DashAI/back/tasks/tabular_classification_task.py
> +    def prepare_for_task(self, datasetdict: DatasetDict):
If the method extends the abstract of the super class, it still has to be documented according to its specific functionality.

2023-05-24 19:27 UTC, pbadillatorrealba commented on DashAI/back/tasks/tabular_classification_task.py
> +        tipos = {outputs_columns[0]: "Categorico"}
```suggestion
        types= {outputs_columns[0]: "Categorical"}
```

2023-05-25 04:35 UTC, Oziel14 commented on tests/back/tasks/iris_extra_feature.csv
because it was made incorrectly and gave another type of error

2023-05-25 05:00 UTC, Oziel14 commented
Added the changes, in the case of the change related to the language it was necessary to change the dashaidataset method that changes the types and consequently some tests of these.

2023-05-25 14:38 UTC, pbadillatorrealba approved these changes

2023-05-25 14:39 UTC, merged