Edit dataset
DashAISoftware/DashAI pull request #76
Opened 2023-05-24 22:46 UTC by maximi4321

# Summary

Includes a modal to change the name and task associated with a dataset

## Type of change

- Front end new feature.

## Changes

- Add a modal with a TextField to change the name of a dataset and also renders `ItemSelector.jsx` to change the task associated to the dataset
- updates the Datasets table once the update is done

## How to Test

Option 1 - Backend
1. Go to `DashAI/DashAI/front` and run `yarn build`
2. Go back to `DashAI/` and run `python -c "import DashAI;DashAI.run()`
3. Navigate to the datasets tab
4.  Click the button to edit dataset (requires at least one dataset in the table)
5. Modify the name and the task and click "Save"
6. The modified values should be updated in the datasets table.

Option 2 - json-server
1. Go to `DashAI/DashAI/front` and run `yarn json-server`
2. in another terminal in the same folder of step 1 run `yarn start`
4. Navigate to the datasets tab
5.  Click the button to edit dataset (requires at least one dataset in the table)
6. Modify the name and the task (this option doesn't support updating the values in the table)

## Screenshots

![edit-dataset](https://github.com/DashAISoftware/DashAI/assets/53657198/83587ec6-be63-4fe9-ba3f-933846f9f155)

## Notes

This PR depends on #75

2023-05-26 01:50 UTC, pbadillatorrealba requested changes
I think the idea of editing tasks is good but I strongly recommend disabling it. Next I explain why:

Changing the name is simple, just modify the name in the DB and that's it; now all objects that depend on the dataset will see the new name (assuming the id will remain the same).

However, changing the task would mean that all the experiments that depend on this dataset would have none associated with it. In that case, actions must be taken to prevent this from happening. Therefore, the easiest thing to do is to disable editing.

Interesting note: we should also think about what to do when deleting a dataset in the future. I am of the idea of only allowing the deletion of datasets that do not have any associated experiment.

2023-06-01 15:00 UTC, pbadillatorrealba requested changes
As I understood, you only disabled task editing, but did not delete it?

I left a last API design comment. It's pretty brief, but probably also requires a change in the back end.

2023-06-01 15:00 UTC, pbadillatorrealba commented on DashAI/front/src/components/custom/ItemSelector.jsx
> +  // DialogContentText,
```suggestion
```

2023-06-01 15:00 UTC, pbadillatorrealba commented on DashAI/front/src/components/EditDatasetModal.jsx
> +  // ButtonGroup,
```suggestion
```

2023-06-01 15:00 UTC, pbadillatorrealba commented on DashAI/front/src/api/datasets.ts
> +  return response.data;
As convention, POST, PUT, PATCH should deliver the new data in the request body.
On the other hand, when the resource is already created and you want to modify it (in PUT and PATCH), it must be accessed through Paths (i.e., datasets/1, etc.).

To get an idea, this could be read as: 
_Update the dataset with id=1 with the json data provided in the body._

```suggestion
  const response = await api.patch<IDataset>(
    `${datasetEndpoint}/${id}`,
    {"name": name, "task_name":  task_name}
  );
  return response.data;
```

2023-06-01 20:04 UTC, maximi4321 commented on DashAI/front/src/api/datasets.ts
> +  return response.data;
Thank you!

I fixed it using the same method as for solving the post request in the case of uploading an experiment, passing the elements of the object as formData.

The modifications on the backend to make it work are similar: add `Form(...)` to each parameter that requires it.

2023-06-07 01:13 UTC, pbadillatorrealba approved these changes
Approved!

2023-06-07 21:58 UTC, merged