Back/refactor tests
DashAISoftware/DashAI pull request #83
Opened 2023-06-02 23:11 UTC by Oziel14

# Summary

We made a refactor to the tests such as renaming, reorganization of some things according to past comments and elimination of resources.

## Type of change

- Refactoring.

## Changes

## How to Test

It is enough to launch the tests

## Notes

Depends on the PR #78

2023-06-05 14:39 UTC, Riul1999 requested changes
Overall, the changes are positive

But i think there are still some changes to be made:
- The test for dataloaders still create and do not delete the dashaidataset folder, which should be deleted in the last test that used it or in a conftest fixture teardown (after all tests of the dataloaders package run).
- The test for models should create and manage its own dashaidataset, instead of using the one created by the test for dataloaders.

I also leave a comment for the load_data function that I think it is good to think about it.

2023-06-05 14:39 UTC, Riul1999 commented on tests/back/dataloaders/test_dataloaders.py
> +    os.remove(
I think this remove should be inside the load_data function, in a finally statement

2023-06-07 01:48 UTC, pbadillatorrealba commented
Also remember to resolve conflicts!

2023-06-09 16:31 UTC, Oziel14 commented
Done!

2023-06-12 14:39 UTC, Riul1999 approved these changes

2023-06-12 14:47 UTC, merged