Asynchronous Runner
DashAISoftware/DashAI pull request #91
Opened 2023-06-09 13:26 UTC by Riul1999

# Summary

Refactor the **Runner** to run _asynchronously_ in the backend, this allows requests to be made while a **Run** is being processed.

## Type of change

- Back end new feature.
- Refactoring.

## Changes

- Created the _execute_runner_ function inside _core/runner.py_, this function is in charge of executing a **Run** and storing all data of interest.
- Refactored the runner endpoint, now it just checks if all the **Components** and database objects are available and then passes it to _execute_run_.
- In the endpoint runner, the execution of _execute_run_ is performed asynchronously, using FastAPI **BackgroundTasks**.
- New RunStatus **DELIVERED** has been added, this status is used when the execution has been passed to the background (after a request from the runner endpoint) but the execution is not processed by the _execute_run_ function.
- Modified _test_runner_ to check the asynchrony of the runner endpoint, checks (while the runner is training the **Run**) the state of the **Run**.

## How to Test

To test it's necesary to run `pytest ./tests/back/api/test_runner.py`

2023-06-13 18:42 UTC, pbadillatorrealba requested changes
Looks good and is easy to read :)

I left some code style and names comments and also a question about the error handling.

2023-06-13 18:42 UTC, pbadillatorrealba commented on DashAI/back/database/models.py
> +    def run_delivery(self):
Why not to call the state changer method with a slightly more descriptive name as `set_status_as_delivered`?
This change could be easily extended to the remaining state changing methods. (`set_status_as_started` and `set_status_as_finished`).

```suggestion
    def set_status_as_delivered(self):
```

2023-06-13 18:42 UTC, pbadillatorrealba commented on tests/back/api/test_runner.py
> +    assert type(data["test_metrics"]) is dict
Use `isinstance` instead:

```suggestion
    assert isinstance(data["train_metrics"], dict)
    assert isinstance(data["validation_metrics"], dict)
    assert isinstance(data["test_metrics"], dict)
```

2023-06-13 18:42 UTC, pbadillatorrealba commented on DashAI/back/api/api_v1/endpoints/runner.py
> +    background_tasks.add_task(
What happens if an exception is raised inside the background task?
Where do you set a run as failed?
My guess is that it is missing a try-except somewhere. 
This try-except should log some error message and modify the run status as failed.

2023-06-14 20:44 UTC, cristian-tamblay requested changes
PR is almost good to be merged, I think we should think a bit how to handle exceptions in training. Give it a though and we merge.

2023-06-14 20:44 UTC, cristian-tamblay commented on DashAI/back/core/runner.py
> +        ) from e
I think this exception catching is too general, and the raise RunnerError makes it even worse, now the user wont know what caused the exception. A bare raise is better than raise RunnerError(...). 

I know this is a hard to solve problem, we can at least do the following: we could separate different exceptions such as failed in training or metric evaluation. A good aproach for this is making the try: catch: blocks have less code, as an example, just
```
try:
    model.fit()
except Exception as e:
    log.exception(e)
    run.set_status_as_error()
    db.commit()
    raise RunnerError("Training failed")
finally:...
...
try:
    model.metrics(...)
except Exception as e:
    log.exception(e)
    run.set_status_as_error()
    db.commit()
    raise RunnerError("Metric calculation failed")
finally:...
```

2023-06-14 20:44 UTC, cristian-tamblay commented on tests/back/api/test_runner.py
> +        raise Exception("Allways fails")
typo
```suggestion
        raise Exception("Always fails")
```

2023-06-15 13:59 UTC, cristian-tamblay approved these changes
Exception handling is perfectable, but its good enough for this iteration

2023-06-15 14:00 UTC, merged